version: '3.6'

services:
  recommender:
    container_name: recommender
    build: .
    volumes:
    - .:/add_on_recommender/
    command: bash -c "python3 add_on_recommender.py && python3 predict.py"

  tests:
    container_name: tests
    build: .
    command: nosetests tests/
